In [17]:
import pandas as pd

In [18]:
df1 = pd.read_csv('Final_Rest_Data.csv')
df1

,Restaurant_x,Borough,Grade,aggregate_rating,votes,establishment,Price,Reservation
0,LA FUSTA RESTAURANT,Queens,B,3.9,16,Casual Dining,$$,Yes
1,NOREETUH,Manhattan,A,3.3,9,Casual Dining,$$$,Yes
2,KASHMIR 9,Manhattan,A,3.7,7,Casual Dining,$,No
3,THE SPOT KARAOKE LOUNGE,Manhattan,A,0.0,1,Bar,$$,Yes
4,TURNTABLE LP BAR,Manhattan,A,0.0,1,Bar,$$,Yes
5,KOSHER BAGEL HOLE,Brooklyn,A,0.0,0,Quick Bites,$,No
6,NEW TASTE OF CHINA NY,Queens,A,3.9,16,Casual Dining,$,No
7,PASTIS,Manhattan,A,0.0,0,Quick Bites,$$$,Yes
8,SPACE BILLARD,Manhattan,A,0.0,1,Bar,$$,Yes
9,BARO,Manhattan,A,0.0,1,Bar,NaN,NaN
10,DI FARA PIZZERIA,Brooklyn,A,4.5,250,Quick Bites,$$,No
11,1 DOZEN,Brooklyn,A,3.2,3,Quick Bites,$,No
12,PIO PIO,Manhattan,A,4.4,106,Casual Dining,$$,Yes
13,NUNOODLE,Manhattan,A,3.3,9,Casual Dining,$,No
14,K TOWN,Manhattan,A,0.0,1,Bar,$$,No
15,THREE GUY'S RESTAURANT,Manhattan,A,3.6,31,Casual Dining,$$,No
16,MIRACALI III,Queens,A,3.9,16,Casual Dining,$,No
17,LANDSDOWNE ROAD,Manhattan,A,4.4,106,Casual Dining,$$,No
18,KENNEDY'S FRIED CHICKEN & BISCUITS,Bronx,A,0.0,0,Fast Food,$,No
19,SWEET GENERATION,Manhattan,A,3.3,9,Casual Dining,$$,NaN
20,DUBUMARU,Manhattan,A,0.0,1,Bar,$$,No
21,SPACE KARAOKE,Manhattan,A,0.0,1,Bar,$$,Yes
22,LUCKY THAILAND KITCHEN,Queens,B,0.0,0,Quick Bites,NaN,NaN
23,STONE CREEK,Manhattan,A,2.8,4,Casual Dining,$$,Yes
24,NUR,Manhattan,A,3.1,4,Casual Dining,$$$,Yes
25,BLAZE PIZZA,Staten Island,A,0.0,0,Pizzaria,$,No
26,DESI GALLI,Manhattan,B,3.7,18,Casual Dining,$,Yes
27,BELLA VITA PORK STORE,Staten Island,A,3.3,1,Deli,$$,No
28,FUSHIMI JAPANESE CUISINE,Brooklyn,A,3.8,23,Casual Dining,$$,Yes
29,DUNKIN,Brooklyn,A,2.8,3,Coffee Shop,$,NaN
30,BAKEWAY,Queens,C,0.0,0,Cafe,$,NaN
31,JOE'S SHANGHAI RESTAURANT,Queens,C,4.5,109,Casual Dining,$$,Yes
32,ROSELLA'S PIZZERIA,Manhattan,B,3.8,22,Pizzaria,$,No
33,NEW BOE LEE,Bronx,A,3.8,4,Quick Bites,$,No
34,KRUPA GROCERY,Brooklyn,A,2.8,4,Casual Dining,$$,Yes
35,Taco King,Queens,A,4.6,33,Quick Bites,$,No
36,Le Bernardin,Manhattan,A,4.7,679,Fine Dining,$$$$,Yes

In [3]:
df1= df1.rename(index=str, columns={'aggregate_rating': 'User Rating','votes': 'Number of Reviews','establishment':'Establishment','Price':'Price Range'})
df1

,Restaurant_x,Borough,Grade,User Rating,Number of Reviews,Establishment,Price Range,Reservation
0,LA FUSTA RESTAURANT,Queens,B,3.9,16,Casual Dining,$$,Yes
1,NOREETUH,Manhattan,A,3.3,9,Casual Dining,$$$,Yes
2,KASHMIR 9,Manhattan,A,3.7,7,Casual Dining,$,No
3,THE SPOT KARAOKE LOUNGE,Manhattan,A,0.0,1,Bar,$$,Yes
4,TURNTABLE LP BAR,Manhattan,A,0.0,1,Bar,$$,Yes
5,KOSHER BAGEL HOLE,Brooklyn,A,0.0,0,Quick Bites,$,No
6,NEW TASTE OF CHINA NY,Queens,A,3.9,16,Casual Dining,$,No
7,PASTIS,Manhattan,A,0.0,0,Quick Bites,$$$,Yes
8,SPACE BILLARD,Manhattan,A,0.0,1,Bar,$$,Yes
9,BARO,Manhattan,A,0.0,1,Bar,NaN,NaN
10,DI FARA PIZZERIA,Brooklyn,A,4.5,250,Quick Bites,$$,No
11,1 DOZEN,Brooklyn,A,3.2,3,Quick Bites,$,No
12,PIO PIO,Manhattan,A,4.4,106,Casual Dining,$$,Yes
13,NUNOODLE,Manhattan,A,3.3,9,Casual Dining,$,No
14,K TOWN,Manhattan,A,0.0,1,Bar,$$,No
15,THREE GUY'S RESTAURANT,Manhattan,A,3.6,31,Casual Dining,$$,No
16,MIRACALI III,Queens,A,3.9,16,Casual Dining,$,No
17,LANDSDOWNE ROAD,Manhattan,A,4.4,106,Casual Dining,$$,No
18,KENNEDY'S FRIED CHICKEN & BISCUITS,Bronx,A,0.0,0,Fast Food,$,No
19,SWEET GENERATION,Manhattan,A,3.3,9,Casual Dining,$$,NaN
20,DUBUMARU,Manhattan,A,0.0,1,Bar,$$,No
21,SPACE KARAOKE,Manhattan,A,0.0,1,Bar,$$,Yes
22,LUCKY THAILAND KITCHEN,Queens,B,0.0,0,Quick Bites,NaN,NaN
23,STONE CREEK,Manhattan,A,2.8,4,Casual Dining,$$,Yes
24,NUR,Manhattan,A,3.1,4,Casual Dining,$$$,Yes
25,BLAZE PIZZA,Staten Island,A,0.0,0,Pizzaria,$,No
26,DESI GALLI,Manhattan,B,3.7,18,Casual Dining,$,Yes
27,BELLA VITA PORK STORE,Staten Island,A,3.3,1,Deli,$$,No
28,FUSHIMI JAPANESE CUISINE,Brooklyn,A,3.8,23,Casual Dining,$$,Yes
29,DUNKIN,Brooklyn,A,2.8,3,Coffee Shop,$,NaN
30,BAKEWAY,Queens,C,0.0,0,Cafe,$,NaN
31,JOE'S SHANGHAI RESTAURANT,Queens,C,4.5,109,Casual Dining,$$,Yes
32,ROSELLA'S PIZZERIA,Manhattan,B,3.8,22,Pizzaria,$,No
33,NEW BOE LEE,Bronx,A,3.8,4,Quick Bites,$,No
34,KRUPA GROCERY,Brooklyn,A,2.8,4,Casual Dining,$$,Yes
35,Taco King,Queens,A,4.6,33,Quick Bites,$,No

In [4]:
final_data = df1.drop(['Restaurant_x'], axis=1)
final_data

,Borough,Grade,User Rating,Number of Reviews,Establishment,Price Range,Reservation
0,Queens,B,3.9,16,Casual Dining,$$,Yes
1,Manhattan,A,3.3,9,Casual Dining,$$$,Yes
2,Manhattan,A,3.7,7,Casual Dining,$,No
3,Manhattan,A,0.0,1,Bar,$$,Yes
4,Manhattan,A,0.0,1,Bar,$$,Yes
5,Brooklyn,A,0.0,0,Quick Bites,$,No
6,Queens,A,3.9,16,Casual Dining,$,No
7,Manhattan,A,0.0,0,Quick Bites,$$$,Yes
8,Manhattan,A,0.0,1,Bar,$$,Yes
9,Manhattan,A,0.0,1,Bar,NaN,NaN
10,Brooklyn,A,4.5,250,Quick Bites,$$,No
11,Brooklyn,A,3.2,3,Quick Bites,$,No
12,Manhattan,A,4.4,106,Casual Dining,$$,Yes
13,Manhattan,A,3.3,9,Casual Dining,$,No
14,Manhattan,A,0.0,1,Bar,$$,No
15,Manhattan,A,3.6,31,Casual Dining,$$,No
16,Queens,A,3.9,16,Casual Dining,$,No
17,Manhattan,A,4.4,106,Casual Dining,$$,No
18,Bronx,A,0.0,0,Fast Food,$,No
19,Manhattan,A,3.3,9,Casual Dining,$$,NaN
20,Manhattan,A,0.0,1,Bar,$$,No
21,Manhattan,A,0.0,1,Bar,$$,Yes
22,Queens,B,0.0,0,Quick Bites,NaN,NaN
23,Manhattan,A,2.8,4,Casual Dining,$$,Yes
24,Manhattan,A,3.1,4,Casual Dining,$$$,Yes
25,Staten Island,A,0.0,0,Pizzaria,$,No
26,Manhattan,B,3.7,18,Casual Dining,$,Yes
27,Staten Island,A,3.3,1,Deli,$$,No
28,Brooklyn,A,3.8,23,Casual Dining,$$,Yes
29,Brooklyn,A,2.8,3,Coffee Shop,$,NaN
30,Queens,C,0.0,0,Cafe,$,NaN
31,Queens,C,4.5,109,Casual Dining,$$,Yes
32,Manhattan,B,3.8,22,Pizzaria,$,No
33,Bronx,A,3.8,4,Quick Bites,$,No
34,Brooklyn,A,2.8,4,Casual Dining,$$,Yes
35,Queens,A,4.6,33,Quick Bites,$,No

In [5]:
print(final_data['Number of Reviews'].mean())
print(final_data['Number of Reviews'].std())

22.5
48.7456957806826

In [8]:
#for number of reviews greater than mean
final_data['Reviews'] = final_data['Number of Reviews'].apply(lambda x: 'low' if x < 22 else 'high')

In [9]:
final_data

,Borough,Grade,User Rating,Number of Reviews,Establishment,Price Range,Reservation,Reviews
0,Queens,B,3.9,16,Casual Dining,$$,Yes,low
1,Manhattan,A,3.3,9,Casual Dining,$$$,Yes,low
2,Manhattan,A,3.7,7,Casual Dining,$,No,low
3,Manhattan,A,0.0,1,Bar,$$,Yes,low
4,Manhattan,A,0.0,1,Bar,$$,Yes,low
5,Brooklyn,A,0.0,0,Quick Bites,$,No,low
6,Queens,A,3.9,16,Casual Dining,$,No,low
7,Manhattan,A,0.0,0,Quick Bites,$$$,Yes,low
8,Manhattan,A,0.0,1,Bar,$$,Yes,low
9,Manhattan,A,0.0,1,Bar,NaN,NaN,low
10,Brooklyn,A,4.5,250,Quick Bites,$$,No,high
11,Brooklyn,A,3.2,3,Quick Bites,$,No,low
12,Manhattan,A,4.4,106,Casual Dining,$$,Yes,high
13,Manhattan,A,3.3,9,Casual Dining,$,No,low
14,Manhattan,A,0.0,1,Bar,$$,No,low
15,Manhattan,A,3.6,31,Casual Dining,$$,No,high
16,Queens,A,3.9,16,Casual Dining,$,No,low
17,Manhattan,A,4.4,106,Casual Dining,$$,No,high
18,Bronx,A,0.0,0,Fast Food,$,No,low
19,Manhattan,A,3.3,9,Casual Dining,$$,NaN,low
20,Manhattan,A,0.0,1,Bar,$$,No,low
21,Manhattan,A,0.0,1,Bar,$$,Yes,low
22,Queens,B,0.0,0,Quick Bites,NaN,NaN,low
23,Manhattan,A,2.8,4,Casual Dining,$$,Yes,low
24,Manhattan,A,3.1,4,Casual Dining,$$$,Yes,low
25,Staten Island,A,0.0,0,Pizzaria,$,No,low
26,Manhattan,B,3.7,18,Casual Dining,$,Yes,low
27,Staten Island,A,3.3,1,Deli,$$,No,low
28,Brooklyn,A,3.8,23,Casual Dining,$$,Yes,high
29,Brooklyn,A,2.8,3,Coffee Shop,$,NaN,low
30,Queens,C,0.0,0,Cafe,$,NaN,low
31,Queens,C,4.5,109,Casual Dining,$$,Yes,high
32,Manhattan,B,3.8,22,Pizzaria,$,No,high
33,Bronx,A,3.8,4,Quick Bites,$,No,low
34,Brooklyn,A,2.8,4,Casual Dining,$$,Yes,low
35,Queens,A,4.6,33,Quick Bites,$,No,high

In [10]:
final_data['Rating'] = final_data['User Rating'].astype(int)
final_data['Rating'] = final_data['Rating'].astype(str)
final_data

,Borough,Grade,User Rating,Number of Reviews,Establishment,Price Range,Reservation,Reviews,Rating
0,Queens,B,3.9,16,Casual Dining,$$,Yes,low,3
1,Manhattan,A,3.3,9,Casual Dining,$$$,Yes,low,3
2,Manhattan,A,3.7,7,Casual Dining,$,No,low,3
3,Manhattan,A,0.0,1,Bar,$$,Yes,low,0
4,Manhattan,A,0.0,1,Bar,$$,Yes,low,0
5,Brooklyn,A,0.0,0,Quick Bites,$,No,low,0
6,Queens,A,3.9,16,Casual Dining,$,No,low,3
7,Manhattan,A,0.0,0,Quick Bites,$$$,Yes,low,0
8,Manhattan,A,0.0,1,Bar,$$,Yes,low,0
9,Manhattan,A,0.0,1,Bar,NaN,NaN,low,0
10,Brooklyn,A,4.5,250,Quick Bites,$$,No,high,4
11,Brooklyn,A,3.2,3,Quick Bites,$,No,low,3
12,Manhattan,A,4.4,106,Casual Dining,$$,Yes,high,4
13,Manhattan,A,3.3,9,Casual Dining,$,No,low,3
14,Manhattan,A,0.0,1,Bar,$$,No,low,0
15,Manhattan,A,3.6,31,Casual Dining,$$,No,high,3
16,Queens,A,3.9,16,Casual Dining,$,No,low,3
17,Manhattan,A,4.4,106,Casual Dining,$$,No,high,4
18,Bronx,A,0.0,0,Fast Food,$,No,low,0
19,Manhattan,A,3.3,9,Casual Dining,$$,NaN,low,3
20,Manhattan,A,0.0,1,Bar,$$,No,low,0
21,Manhattan,A,0.0,1,Bar,$$,Yes,low,0
22,Queens,B,0.0,0,Quick Bites,NaN,NaN,low,0
23,Manhattan,A,2.8,4,Casual Dining,$$,Yes,low,2
24,Manhattan,A,3.1,4,Casual Dining,$$$,Yes,low,3
25,Staten Island,A,0.0,0,Pizzaria,$,No,low,0
26,Manhattan,B,3.7,18,Casual Dining,$,Yes,low,3
27,Staten Island,A,3.3,1,Deli,$$,No,low,3
28,Brooklyn,A,3.8,23,Casual Dining,$$,Yes,high,3
29,Brooklyn,A,2.8,3,Coffee Shop,$,NaN,low,2
30,Queens,C,0.0,0,Cafe,$,NaN,low,0
31,Queens,C,4.5,109,Casual Dining,$$,Yes,high,4
32,Manhattan,B,3.8,22,Pizzaria,$,No,high,3
33,Bronx,A,3.8,4,Quick Bites,$,No,low,3
34,Brooklyn,A,2.8,4,Casual Dining,$$,Yes,low,2
35,Queens,A,4.6,33,Quick Bites,$,No,high,4

In [11]:
final_data_clean = final_data.drop(['User Rating','Number of Reviews'], axis=1)
final_data_clean

,Borough,Grade,Establishment,Price Range,Reservation,Reviews,Rating
0,Queens,B,Casual Dining,$$,Yes,low,3
1,Manhattan,A,Casual Dining,$$$,Yes,low,3
2,Manhattan,A,Casual Dining,$,No,low,3
3,Manhattan,A,Bar,$$,Yes,low,0
4,Manhattan,A,Bar,$$,Yes,low,0
5,Brooklyn,A,Quick Bites,$,No,low,0
6,Queens,A,Casual Dining,$,No,low,3
7,Manhattan,A,Quick Bites,$$$,Yes,low,0
8,Manhattan,A,Bar,$$,Yes,low,0
9,Manhattan,A,Bar,NaN,NaN,low,0
10,Brooklyn,A,Quick Bites,$$,No,high,4
11,Brooklyn,A,Quick Bites,$,No,low,3
12,Manhattan,A,Casual Dining,$$,Yes,high,4
13,Manhattan,A,Casual Dining,$,No,low,3
14,Manhattan,A,Bar,$$,No,low,0
15,Manhattan,A,Casual Dining,$$,No,high,3
16,Queens,A,Casual Dining,$,No,low,3
17,Manhattan,A,Casual Dining,$$,No,high,4
18,Bronx,A,Fast Food,$,No,low,0
19,Manhattan,A,Casual Dining,$$,NaN,low,3
20,Manhattan,A,Bar,$$,No,low,0
21,Manhattan,A,Bar,$$,Yes,low,0
22,Queens,B,Quick Bites,NaN,NaN,low,0
23,Manhattan,A,Casual Dining,$$,Yes,low,2
24,Manhattan,A,Casual Dining,$$$,Yes,low,3
25,Staten Island,A,Pizzaria,$,No,low,0
26,Manhattan,B,Casual Dining,$,Yes,low,3
27,Staten Island,A,Deli,$$,No,low,3
28,Brooklyn,A,Casual Dining,$$,Yes,high,3
29,Brooklyn,A,Coffee Shop,$,NaN,low,2
30,Queens,C,Cafe,$,NaN,low,0
31,Queens,C,Casual Dining,$$,Yes,high,4
32,Manhattan,B,Pizzaria,$,No,high,3
33,Bronx,A,Quick Bites,$,No,low,3
34,Brooklyn,A,Casual Dining,$$,Yes,low,2
35,Queens,A,Quick Bites,$,No,high,4

In [12]:
import arff
arff.dump('final-restaurants-cleaned.arff'
      , final_data_clean.values
      , relation='final-restaurants-cleaned'
      , names=final_data_clean.columns)