In [89]:
import pandas as pd

In [90]:
zomato_data = pd.read_csv('./Downloads/zomato_output.csv')
zomato_data

,Unnamed: 0,Restaurant_x,Borough,Grade,Latitude,Longitude,Restaurant_y,aggregate_rating,votes,establishment
0,0,LA FUSTA RESTAURANT,Queens,B,40.7447,-73.8846,La Fusta,3.9,16,Casual Dining
1,1,NOREETUH,Manhattan,A,40.7274,-73.9854,Noreetuh,3.3,9,Casual Dining
2,2,KASHMIR 9,Manhattan,A,40.7551,-73.9951,Kashmir Cuisine of Pakistan,3.7,7,Casual Dining
3,3,THE SPOT KARAOKE LOUNGE,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
4,5,TURNTABLE LP BAR,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
5,6,KOSHER BAGEL HOLE,Brooklyn,A,40.6251,-73.9620,Baguette Express,0.0,0,Quick Bites
6,7,NEW TASTE OF CHINA NY,Queens,A,40.7447,-73.8846,La Fusta,3.9,16,Casual Dining
7,8,PASTIS,Manhattan,A,40.7394,-74.0070,Feel Food,0.0,0,Quick Bites
8,11,SPACE BILLARD,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
9,13,BARO,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
10,14,DI FARA PIZZERIA,Brooklyn,A,40.6251,-73.9620,Baguette Express,0.0,0,Quick Bites
11,19,1 DOZEN,Brooklyn,A,40.6616,-73.9860,Joy Kitchen,3.2,3,Quick Bites
12,20,PIO PIO,Manhattan,A,40.7606,-73.9948,Pio Pio 8,4.4,106,Casual Dining
13,22,NUNOODLE,Manhattan,A,40.7274,-73.9854,Noreetuh,3.3,9,Casual Dining
14,23,K TOWN,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
15,27,THREE GUY'S RESTAURANT,Manhattan,A,40.7740,-73.9638,3 Guys Restaurant,3.6,31,Casual Dining
16,35,MIRACALI III,Queens,A,40.7447,-73.8846,La Fusta,3.9,16,Casual Dining
17,48,LANDSDOWNE ROAD,Manhattan,A,40.7606,-73.9948,Pio Pio 8,4.4,106,Casual Dining
18,52,KENNEDY'S FRIED CHICKEN & BISCUITS,Bronx,A,40.8575,-73.8911,Kennedy Fried Chicken,0.0,0,Fast Food
19,60,SWEET GENERATION,Manhattan,A,40.7274,-73.9854,Noreetuh,3.3,9,Casual Dining
20,65,DUBUMARU,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
21,159,SPACE KARAOKE,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar

In [91]:
zomato_data = zomato_data.rename(index=str, columns={'aggregate_rating': 'User Rating','votes': 'Number of Reviews','establishment':'Establishment'})
zomato_data

,Unnamed: 0,Restaurant_x,Borough,Grade,Latitude,Longitude,Restaurant_y,User Rating,Number of Reviews,Establishment
0,0,LA FUSTA RESTAURANT,Queens,B,40.7447,-73.8846,La Fusta,3.9,16,Casual Dining
1,1,NOREETUH,Manhattan,A,40.7274,-73.9854,Noreetuh,3.3,9,Casual Dining
2,2,KASHMIR 9,Manhattan,A,40.7551,-73.9951,Kashmir Cuisine of Pakistan,3.7,7,Casual Dining
3,3,THE SPOT KARAOKE LOUNGE,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
4,5,TURNTABLE LP BAR,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
5,6,KOSHER BAGEL HOLE,Brooklyn,A,40.6251,-73.9620,Baguette Express,0.0,0,Quick Bites
6,7,NEW TASTE OF CHINA NY,Queens,A,40.7447,-73.8846,La Fusta,3.9,16,Casual Dining
7,8,PASTIS,Manhattan,A,40.7394,-74.0070,Feel Food,0.0,0,Quick Bites
8,11,SPACE BILLARD,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
9,13,BARO,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
10,14,DI FARA PIZZERIA,Brooklyn,A,40.6251,-73.9620,Baguette Express,0.0,0,Quick Bites
11,19,1 DOZEN,Brooklyn,A,40.6616,-73.9860,Joy Kitchen,3.2,3,Quick Bites
12,20,PIO PIO,Manhattan,A,40.7606,-73.9948,Pio Pio 8,4.4,106,Casual Dining
13,22,NUNOODLE,Manhattan,A,40.7274,-73.9854,Noreetuh,3.3,9,Casual Dining
14,23,K TOWN,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
15,27,THREE GUY'S RESTAURANT,Manhattan,A,40.7740,-73.9638,3 Guys Restaurant,3.6,31,Casual Dining
16,35,MIRACALI III,Queens,A,40.7447,-73.8846,La Fusta,3.9,16,Casual Dining
17,48,LANDSDOWNE ROAD,Manhattan,A,40.7606,-73.9948,Pio Pio 8,4.4,106,Casual Dining
18,52,KENNEDY'S FRIED CHICKEN & BISCUITS,Bronx,A,40.8575,-73.8911,Kennedy Fried Chicken,0.0,0,Fast Food
19,60,SWEET GENERATION,Manhattan,A,40.7274,-73.9854,Noreetuh,3.3,9,Casual Dining
20,65,DUBUMARU,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar
21,159,SPACE KARAOKE,Manhattan,A,40.7478,-73.9871,WABar,0.0,1,Bar

In [93]:
zomato_data_clean = zomato_data[['Borough','Grade','Number of Reviews','Establishment','User Rating']]
zomato_data_clean

      Borough Grade  Number of Reviews  Establishment  User Rating
0      Queens     B                 16  Casual Dining          3.9
1   Manhattan     A                  9  Casual Dining          3.3
2   Manhattan     A                  7  Casual Dining          3.7
3   Manhattan     A                  1            Bar          0.0
4   Manhattan     A                  1            Bar          0.0
5    Brooklyn     A                  0    Quick Bites          0.0
6      Queens     A                 16  Casual Dining          3.9
7   Manhattan     A                  0    Quick Bites          0.0
8   Manhattan     A                  1            Bar          0.0
9   Manhattan     A                  1            Bar          0.0
10   Brooklyn     A                  0    Quick Bites          0.0
11   Brooklyn     A                  3    Quick Bites          3.2
12  Manhattan     A                106  Casual Dining          4.4
13  Manhattan     A                  9  Casual Dining          3.3
14  Manhattan     A                  1            Bar          0.0
15  Manhattan     A                 31  Casual Dining          3.6
16     Queens     A                 16  Casual Dining          3.9
17  Manhattan     A                106  Casual Dining          4.4
18      Bronx     A                  0      Fast Food          0.0
19  Manhattan     A                  9  Casual Dining          3.3
20  Manhattan     A                  1            Bar          0.0
21  Manhattan     A                  1            Bar          0.0

In [94]:
zomato_data_clean['Number of Reviews'] = zomato_data_clean['Number of Reviews'].astype(int)
zomato_data_clean['User Rating'] = zomato_data_clean['User Rating'].astype(float)

/Users/shreyagurjar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/shreyagurjar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [95]:
zomato_data_clean['Number of Reviews'].mean()

15.227272727272727

In [100]:
zomato_data_clean['Reviews'] = zomato_data_clean['Number of Reviews'].apply(lambda x: 'low' if x < 15 else 'high')

/Users/shreyagurjar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [101]:
zomato_data_clean

,Borough,Grade,Number of Reviews,Establishment,User Rating,Reviews,Rating,Reviews
0,Queens,B,16,Casual Dining,3.9,high,4.0,high
1,Manhattan,A,9,Casual Dining,3.3,low,3.0,low
2,Manhattan,A,7,Casual Dining,3.7,low,4.0,low
3,Manhattan,A,1,Bar,0.0,low,0.0,low
4,Manhattan,A,1,Bar,0.0,low,0.0,low
5,Brooklyn,A,0,Quick Bites,0.0,low,0.0,low
6,Queens,A,16,Casual Dining,3.9,high,4.0,high
7,Manhattan,A,0,Quick Bites,0.0,low,0.0,low
8,Manhattan,A,1,Bar,0.0,low,0.0,low
9,Manhattan,A,1,Bar,0.0,low,0.0,low
10,Brooklyn,A,0,Quick Bites,0.0,low,0.0,low
11,Brooklyn,A,3,Quick Bites,3.2,low,3.0,low
12,Manhattan,A,106,Casual Dining,4.4,high,4.0,high
13,Manhattan,A,9,Casual Dining,3.3,low,3.0,low
14,Manhattan,A,1,Bar,0.0,low,0.0,low
15,Manhattan,A,31,Casual Dining,3.6,high,4.0,high
16,Queens,A,16,Casual Dining,3.9,high,4.0,high
17,Manhattan,A,106,Casual Dining,4.4,high,4.0,high
18,Bronx,A,0,Fast Food,0.0,low,0.0,low
19,Manhattan,A,9,Casual Dining,3.3,low,3.0,low
20,Manhattan,A,1,Bar,0.0,low,0.0,low
21,Manhattan,A,1,Bar,0.0,low,0.0,low

In [102]:
zomato_data_clean['Rating'] = zomato_data_clean['User Rating'].round()
zomato_data_clean

/Users/shreyagurjar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Borough,Grade,Number of Reviews,Establishment,User Rating,Reviews,Rating,Reviews
0,Queens,B,16,Casual Dining,3.9,high,4.0,high
1,Manhattan,A,9,Casual Dining,3.3,low,3.0,low
2,Manhattan,A,7,Casual Dining,3.7,low,4.0,low
3,Manhattan,A,1,Bar,0.0,low,0.0,low
4,Manhattan,A,1,Bar,0.0,low,0.0,low
5,Brooklyn,A,0,Quick Bites,0.0,low,0.0,low
6,Queens,A,16,Casual Dining,3.9,high,4.0,high
7,Manhattan,A,0,Quick Bites,0.0,low,0.0,low
8,Manhattan,A,1,Bar,0.0,low,0.0,low
9,Manhattan,A,1,Bar,0.0,low,0.0,low
10,Brooklyn,A,0,Quick Bites,0.0,low,0.0,low
11,Brooklyn,A,3,Quick Bites,3.2,low,3.0,low
12,Manhattan,A,106,Casual Dining,4.4,high,4.0,high
13,Manhattan,A,9,Casual Dining,3.3,low,3.0,low
14,Manhattan,A,1,Bar,0.0,low,0.0,low
15,Manhattan,A,31,Casual Dining,3.6,high,4.0,high
16,Queens,A,16,Casual Dining,3.9,high,4.0,high
17,Manhattan,A,106,Casual Dining,4.4,high,4.0,high
18,Bronx,A,0,Fast Food,0.0,low,0.0,low
19,Manhattan,A,9,Casual Dining,3.3,low,3.0,low
20,Manhattan,A,1,Bar,0.0,low,0.0,low
21,Manhattan,A,1,Bar,0.0,low,0.0,low

In [105]:
zomato_data_clean['Rating'] = zomato_data_clean['Rating'].astype(str)

/Users/shreyagurjar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [106]:
zomato_data_transform= zomato_data_clean[['Borough','Grade','Reviews','Establishment','Rating']]
zomato_data_transform

      Borough Grade Reviews  Establishment Rating
0      Queens     B    high  Casual Dining    4.0
1   Manhattan     A     low  Casual Dining    3.0
2   Manhattan     A     low  Casual Dining    4.0
3   Manhattan     A     low            Bar    0.0
4   Manhattan     A     low            Bar    0.0
5    Brooklyn     A     low    Quick Bites    0.0
6      Queens     A    high  Casual Dining    4.0
7   Manhattan     A     low    Quick Bites    0.0
8   Manhattan     A     low            Bar    0.0
9   Manhattan     A     low            Bar    0.0
10   Brooklyn     A     low    Quick Bites    0.0
11   Brooklyn     A     low    Quick Bites    3.0
12  Manhattan     A    high  Casual Dining    4.0
13  Manhattan     A     low  Casual Dining    3.0
14  Manhattan     A     low            Bar    0.0
15  Manhattan     A    high  Casual Dining    4.0
16     Queens     A    high  Casual Dining    4.0
17  Manhattan     A    high  Casual Dining    4.0
18      Bronx     A     low      Fast Food    0.0
19  Manhattan     A     low  Casual Dining    3.0
20  Manhattan     A     low            Bar    0.0
21  Manhattan     A     low            Bar    0.0

In [85]:
!pip install arff

Collecting arff
  Downloading https://files.pythonhosted.org/packages/50/de/62d4446c5a6e459052c2f2d9490c370ddb6abc0766547b4cef585913598d/arff-0.9.tar.gz
Building wheels for collected packages: arff
  Building wheel for arff (setup.py) ... done
  Created wheel for arff: filename=arff-0.9-cp36-none-any.whl size=4971 sha256=23bda0fe819b754bf779b6be2a9b6f3a09c63130629b0ff7e83fbe1dd7b38902
  Stored in directory: /Users/shreyagurjar/Library/Caches/pip/wheels/04/d0/70/2c73afedd3ac25c6085b528742c69b9587cbdfa67e5194583b
Successfully built arff
Installing collected packages: arff
Successfully installed arff-0.9

In [108]:
import arff
arff.dump('restaurants.arff'
      , zomato_data_transform.values
      , relation='restaurants'
      , names=zomato_data_transform.columns)

In [88]:
zomato_data_transform.to_csv('restaurants_output.csv')